### ISSUE TITLE
Question: Releases marked as prerelease

### ISSUE THREAD

**Issue by HanSolo** [alibaba/dragonwell17#11]
Just saw that the releases currently marked as prerelease=true but the packages are already available for download even on the Dragonwell website. Question is if there will be "real" releases or will the JDK17 repo always use prereleases?
Thank's in advance...

**Comment by joeyleeeeeee97** [comment]
@HanSolo , Hi, the prerelease indicates our artifacts is being reviewed and will release soon.
Thanks for the attention
