### ISSUE TITLE
macOS compile error: Build failure on macOS with Xcode 13.0 as vfork is deprecated

### ISSUE THREAD

**Issue by bxvs888** [alibaba/dragonwell17#12]
macOS 12
Xcode 13.0

/Users/gaoyuntao/app/UFM/dragonwell-17.0.1.0.1-12_jdk-17.0.1-ga/src/hotspot/os/posix/os_posix.cpp:1888:26: error: 'vfork' is deprecated: Use posix_spawn or fork [-Werror,-Wdeprecated-declarations]
  pid = prefer_vfork ? ::vfork() : ::fork();
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[3]: *** [/Users/gaoyuntao/app/UFM/dragonwell-17.0.1.0.1-12_jdk-17.0.1-ga/build/macosx-x86_64-server-release/hotspot/variant-server/libjvm/objs/os_posix.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [hotspot-server-libs] Error 2

ERROR: Build failed for target 'images' in configuration 'macosx-x86_64-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-server_libjvm_objs_os_posix.o:
/Users/gaoyuntao/app/UFM/dragonwell-17.0.1.0.1-12_jdk-17.0.1-ga/src/hotspot/os/posix/os_posix.cpp:1888:26: error: 'vfork' is deprecated: Use posix_spawn or fork [-Werror,-Wdeprecated-declarations]
  pid = prefer_vfork ? ::vfork() : ::fork();
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.

* All command lines available in /Users/gaoyuntao/app/UFM/dragonwell-17.0.1.0.1-12_jdk-17.0.1-ga/build/macosx-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

发现有人在JDK17的bug中。已经在17.0.2修复，这边什么时候能同步这个修复？？

https://bugs.openjdk.java.net/browse/JDK-8274293

**Comment by ziyilin** [comment]
会在下个release和上游同步
