### ISSUE TITLE
Is Dragonwell now a fork of AdoptOpenJDK?

### ISSUE THREAD

**Issue by luchsh** [alibaba/dragonwell17#14]
[README.md](https://github.com/alibaba/dragonwell17/blob/master/README.md) from this repository says:
> Alibaba Dragonwell is clearly a "friendly fork" under the same licensing terms as the upstream OpenJDK project.

But I see tags that only exists in the adoptopenjdk repo, see https://github.com/alibaba/dragonwell17/releases/tag/jdk-17.0.1%2B12_adopt

So 
- Is this official that Dragonwell is now a direct fork of the AdoptOpenJDK project?
- May I have an idea of what else AdoptOpenJDK stuff was included in Dragonwell? maybe not only source code level, but also binaries artifacts.

Thanks

**Comment by joeyleeeeeee97** [comment]
@luchsh .

- Dragonwell is not a direct fork of AdoptOpenJDK,  is from https://github.com/openjdk/jdk17u
- There won't be any AdoptOpenJDK changes on 'master' branch and any release artifacts
- The adopt tag is merely a 'tag' history from other repo so we could compare changes from termurin and dragonwell release(If this is misleading maybe we should delete those)

**Comment by joeyleeeeeee97** [comment]
@luchsh We are forked from openjdk 
![image](https://user-images.githubusercontent.com/30545334/145505073-b2d1229b-0b7c-421d-a679-075984171971.png)

**Comment by joeyleeeeeee97** [comment]
https://github.com/openjdk/jdk17u/releases/tag/jdk-17.0.1-ga
 
from 75240a5872a

**Comment by luchsh** [comment]
> * merely a 'tag' history from other repo

Thanks for the explanation!
Personally I prefer to deleting those tags and be consistent with exactly one upstream.
"merely a 'tag' history from other repo" does not sound good enough, especially for a user who wanna find out certain code's pedigree among his/her sophisticated software supply chain.
