### ISSUE TITLE
Dragonwell 17 Release plan

### ISSUE THREAD

**Issue by joeyleeeeeee97** [alibaba/dragonwell17#2]
## Prepare

- add check.yml
- configure version Number

## Platforms
-  linux-x64
- linux-alpine-x64
-  linux-aarch64
- windows-x64

## Build Jobs
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/
- [x] linux-x64
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-x64-dragonwell/
- [x] linux-alpine-x64
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-alpine-linux-x64-dragonwell/
- [x] linux-aarch64
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-aarch64-dragonwell/
- [x] windows-x64
> 已完成 需要升级到vs2019.
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-windows-x64-dragonwell/

```
10:55:36  openjdk version "17" 2021-09-14
10:55:36  OpenJDK Runtime Environment (Alibaba Dragonwell)-17.0.0+35 (build 17+35)
10:55:36  OpenJDK 64-Bit Server VM (Alibaba Dragonwell)-17.0.0+35 (build 17+35, mixed mode, sharing)
```
## Test Results
http://ci.dragonwell-jdk.io/job/build-scripts/job/openjdk17-pipeline/
### 公开测试
####Linux X86
[Jtreg]
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.openjdk_x86-64_linux/3/testReport/ 通过
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_extended.openjdk_x86-64_linux/2/testReport/ 通过
[System]
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.system_x86-64_linux/23/
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_extended.system_x86-64_linux/17/

#### LinuxArm
[Jtreg]
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.openjdk_aarch64_linux/16/testReport/
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.openjdk_aarch64_linux/16/testReport/
部分失败主要是foreign API相关

[System]
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.system_aarch64_linux/
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_extended.system_aarch64_linux/

#### Windows
http://ci.dragonwell-jdk.io/job/Test_openjdk17_dragonwell_sanity.openjdk_x86-64_windows/2/testReport/ 通过

### 内部测试
specjbb2015通过
**
- http://ci.jvm.alibaba.net/job/ajdk.11.test.perf.specjbb2015/127
- http://ci.jvm.alibaba.net/job/ajdk.11.test.perf.specjbb2015.aarch64/16
- **

### OSS
Done 
### Github Artifacts
https://github.com/alibaba/dragonwell17/releases/tag/dragonwell-17.0.0%2B35_jdk-17-ga
- Check

**Comment by joeyleeeeeee97** [comment]
@Botium1  Hi, 您好, 内部测试部分由于测试材料的原因没有公开, 以ci.dragonwell.io 前缀的测试结果您应该可以看到?
目前包括jtreg 和压力测试结果，如果有关注的框架希望提供测试报告我可以来补充下。

**Comment by xuxiaowei-com-cn** [comment]
我尝试制作了docker版，源码：https://github.com/xuxiaowei-com-cn/dragonwell17
docker hub：https://hub.docker.com/r/xuxiaoweicomcn/dragonwell17
