### ISSUE TITLE
Wrong assets on JDK 17.0.0 release?

### ISSUE THREAD

**Issue by dmikusa-pivotal** [alibaba/dragonwell17#8]
Hi, the assets attached to [the release](https://github.com/alibaba/dragonwell17/releases/tag/dragonwell-17.0.0%2B35_jdk-17-ga) do not look correct.

```
>curl -L -O https://github.com/alibaba/dragonwell17/releases/download/dragonwell-17.0.0%2B35_jdk-17-ga/Alibaba_Dragonwell_17.0.0.35_x64_linux.tar.gz
> tar zxf Alibaba_Dragonwell_17.0.0.35_x64_linux.tar.gz
> tree -L 3
.
└── jdk-17.0.0+35+35-test-image
    ├── Readme.txt
    ├── build-info.properties
    ├── hotspot
    │   └── jtreg
    ├── jdk
    │   ├── demos
    │   └── jtreg
    └── lib-test
        └── jtreg

8 directories, 2 files
```

It looks like the test image download from [here](http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-x64-dragonwell/).

This looks like [the right binary](http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-x64-dragonwell/lastSuccessfulBuild/artifact/workspace/target/OpenJDK17-jdk_x64_linux_dragonwell_2021-10-15-08-03.tar.gz).

**Comment by joeyleeeeeee97** [comment]
@dmikusa-pivotal  Hi. Thanks for the notification. I will redo this release
